Np 9280 implement api endpoints
BIBSYSDEV/nva-courses-api pull request #2
Opened 2022-07-15 12:20 UTC by ketilaa

Current code has assumption that first part of `topLevelOrgCristinId` organization URI matched the FS institution code where the currently logged in user belongs. If FS communication fails for whatever reason, it is logged and an empty list of courses is returned. If the institution is not configured to use FS integration, an empty list of courses is returned.

2022-07-15 14:03 UTC, anetteOlli approved these changes

2022-07-15 14:03 UTC, anetteOlli commented on courses-rest/src/main/java/no/sikt/nva/fs/CoursesByInstitutionOfLoggedInUserHandler.java
> +        if (institutionCode.isPresent()) {
se på nva.attempts hvis du sliter med å få testene til å kjøre innom alle try...catch blokker

2022-07-18 08:20 UTC, axthosarouris requested changes
This is a very big PR. Too much to review. I have only commented on the code style and not what the code does. It should have been broken to many PRs

2022-07-18 08:20 UTC, axthosarouris commented on courses-rest/src/main/java/no/sikt/nva/fs/Course.java
> +    public Course(@JsonProperty("code") final String code,
@JsonCreator annotation is missing. The string literals have to be in sync with the field names for this creator to work. We need to put the same string literals as `@JsonProperty` on the fields as well. 

Alternatively, make the constrcutor a static "create" method and use the default constructor for the serialization

2022-07-18 08:20 UTC, axthosarouris commented on courses-rest/src/main/java/no/sikt/nva/fs/CoursesByInstitutionOfLoggedInUserHandler.java
> +public class CoursesByInstitutionOfLoggedInUserHandler extends ApiGatewayHandler<Void, Course[]> {
We try that NVA returns typed objects because we try to use JSON-LD and we cannot put a type in an array.  Use an object instead, so that we can add the JSON-LD context easily later.

2022-07-18 08:20 UTC, axthosarouris commented on courses-rest/src/main/java/no/sikt/nva/fs/CoursesByInstitutionOfLoggedInUserHandler.java
> +                                                                                currentTime.getMonthValue());
I have no idea what is the intention of the code. Refactor using methods with meaningful names. See #3

2022-07-18 08:20 UTC, axthosarouris commented on courses-rest/src/main/java/no/sikt/nva/fs/CoursesProvider.java
> +    public Course[] getCurrentlyTaughtCourses(final int year, final int month) {
refactor for readability

2022-07-18 08:20 UTC, axthosarouris commented on courses-rest/src/main/java/no/sikt/nva/fs/SystemTimeProvider.java
> +public class SystemTimeProvider implements TimeProvider {
Use Clock to avoid custom production and testing classes

2022-07-18 13:02 UTC, ketilaa commented
I want to go with refactored version on branch NP-9280-implement-api-endpoints-review

2022-07-18 13:02 UTC, closed without merging